# Generated by Django 4.0 on 2022-04-07 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patient_patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('patient_lastname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('gender', models.CharField(choices=[('Женский', 'Женский'), ('Мужской', 'Мужской')], default='Мужской', max_length=20, verbose_name='Пол')),
                ('birth_date', models.DateField(verbose_name='День рождения')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
    ]
